# Generated by Django 2.2.8 on 2020-02-02 14:54

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_auto_20200202_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='thank_you_intro',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
