# Generated by Django 2.2.8 on 2020-02-02 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_contact_thank_you_intro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='thank_you_intro',
            field=models.TextField(),
        ),
    ]
