# Generated by Django 2.2.8 on 2020-01-29 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='intro',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
