# Generated by Django 2.2.8 on 2020-01-29 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mainpage',
            old_name='title_description',
            new_name='header_description',
        ),
        migrations.RenameField(
            model_name='mainpage',
            old_name='page_title',
            new_name='header_title',
        ),
    ]
