# Generated by Django 2.2.8 on 2020-02-03 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('title_description', models.CharField(max_length=500)),
                ('red_intro', models.TextField()),
                ('black_intro', models.TextField()),
                ('intro_description', models.TextField()),
                ('first_offer', models.CharField(max_length=500)),
                ('first_offer_description', models.TextField()),
                ('second_offer', models.CharField(max_length=500)),
                ('second_offer_description', models.TextField()),
                ('third_offer', models.CharField(max_length=500)),
                ('third_offer_description', models.TextField()),
                ('first_step', models.CharField(max_length=500)),
                ('first_step_description', models.TextField()),
                ('second_step', models.CharField(max_length=500)),
                ('second_step_description', models.TextField()),
                ('third_step', models.CharField(max_length=100)),
                ('third_step_description', models.TextField()),
                ('summary_description', models.CharField(max_length=200)),
                ('summary_first', models.CharField(max_length=100)),
                ('summary_first_description', models.TextField()),
                ('summary_second', models.CharField(max_length=100)),
                ('summary_second_description', models.TextField()),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
